### ISSUE TITLE
Model disappearing after loading

### ISSUE THREAD

**Issue by asmaloney** [asmaloney/MeshIO#6]
(By @zyx-99) I'm sorry to bother you again. I use the plug-in to run in cloudcompare2.11.3. When loading COLLADA and glTF model files, the model will only be displayed at the beginning. When I click, rotate, and other operations, it will disappear and become transparent. How should I handle this? Thank you.

When I open the. dae file
![1](https://user-images.githubusercontent.com/103629575/210126500-902f7fd0-9970-448b-ad9b-43bb025e11da.png)

When I rotate an angle. The model disappear.
![2](https://user-images.githubusercontent.com/103629575/210126526-b434bb6e-ad53-4841-8b3a-be0e0798cb86.png)

_Originally posted by @zyx-99 in https://github.com/asmaloney/MeshIO/issues/5#issuecomment-1368169201_

**Comment by asmaloney** [comment]
This sounds like a CloudCompare issue. All this plugin is responsible for is loading the geometry & passing it to CloudCompare which is then responsible for displaying/manipulating it.

It's very hard to tell from this, but it looks like maybe the object is still there (that gray dot in the middle), but the bounding box is huge? Or maybe the geometry collapsed into a singularity?

I'm on macOS, but I'll see if I can reproduce it.

I think your best bet is to create an issue in the CloudCompare repo as well. Someone over there might have some insight.

**Comment by asmaloney** [comment]
I have not been able to reproduce this on macOS, but I'm only set up to build the latest, not the older versions.

Perhaps it's a Windows-only thing? Or an older CC issue?

Can you attach that .dae file to the issue? I have the duck, but I want to make sure it's the same version you're using (e.g. mine's colour, so it's getting textured properly).

**Comment by FrozenCo** [comment]
> I have not been able to reproduce this on macOS, but I'm only set up to build the latest, not the older versions.
> 
> Perhaps it's a Windows-only thing? Or an older CC issue?
> 
> Can you attach that .dae file to the issue? I have the duck, but I want to make sure it's the same version you're using (e.g. mine's colour, so it's getting textured properly).

Hello, I use cloudcompare 2.11.3 assess 5.0.1 and run it on Ubuntu 18.04. The test data is from the test set
assimp-5.0.1/test/models/Collada that comes with assert.
![image](https://user-images.githubusercontent.com/103629575/210160580-c65afd45-4bba-4567-81ce-6718b448776f.png)
What I tested was duck. dae circled in red, which was gray and disappeared after clicking. But the duck in the blue box can be displayed yellow color after I unzip it.Is it because the texture image is not loaded normally? When I uncheck texture, duck. dae becomes a green normal model without texture.
![image](https://user-images.githubusercontent.com/103629575/210160636-0cbb228b-cf8d-4c20-9472-e892f6ee9d47.png)
![image](https://user-images.githubusercontent.com/103629575/210160643-30fa7e29-6728-4178-9ba5-d9ef72e91902.png)

and i test this duck.dae in meshlab on Windows10. It can display normally.
![image](https://user-images.githubusercontent.com/103629575/210160687-ac9afc8b-dd83-4be4-9468-b4d47df8845b.png)

sorry i'm really new in 3Dmodels.Is this because duck.dae can't find the correct texture map file in Ubuntu or cloudcompare, so it loads other gray textures?  However, after duck.zae is unzipped, the yellow duck can be successfully loaded.

**Comment by asmaloney** [comment]
> What I tested was duck. dae circled in red, which was gray 

The `duck.dae` and `duckCM.tga` files go together. If it fails to _find_ the image, you should see a warning in the console:
```
[09:58:48] [MeshIO] Material not found: '/<path>/./duckCM.tga'
```

If the file is there and fails it to _load_ the image, it seems to fail silently. Not sure where the problem lies with this yet.

With a corrupted TGA (to mimic not being able to load it), I end up with the opposite problem you have: the model is invisible until I move the camera.

I'll see if there's anything reasonable I can do if the texture doesn't load properly.

> However, after duck.zae is unzipped, the yellow duck can be successfully loaded.

This is because it uses a PNG instead of a TGA.

In the meantime my suggestions would be (1) use a more recent version of CloudCompare & this plugin and (2) avoid TGA files 😆

**Comment by asmaloney** [comment]
I have added an error if a texture file cannot be read properly (corrupted or unknown format).

In your case, my guess is that the Qt you are using doesn't know how to read TGA files.

**Comment by FrozenCo** [comment]
> > What I tested was duck. dae circled in red, which was gray
> 
> The `duck.dae` and `duckCM.tga` files go together. If it fails to _find_ the image, you should see a warning in the console:
> 
> ```
> [09:58:48] [MeshIO] Material not found: '/<path>/./duckCM.tga'
> ```
> 
> If the file is there and fails it to _load_ the image, it seems to fail silently. Not sure where the problem lies with this yet.
> 
> With a corrupted TGA (to mimic not being able to load it), I end up with the opposite problem you have: the model is invisible until I move the camera.
> 
> I'll see if there's anything reasonable I can do if the texture doesn't load properly.
> 
> > However, after duck.zae is unzipped, the yellow duck can be successfully loaded.
> 
> This is because it uses a PNG instead of a TGA.
> 
> In the meantime my suggestions would be (1) use a more recent version of CloudCompare & this plugin and (2) avoid TGA files 😆

I got it. Thanks for your reply!
