### ISSUE TITLE
Is there a way to test it without having to compile?

### ISSUE THREAD

**Issue by tiagodts** [asmaloney/MeshIO#8]
I'm not a programer, but a heavy CC user. I wonder if there's a way to test and provide feedback without having to compile everything.

**Comment by asmaloney** [comment]
Unfortunately there isn't. CC simply isn't designed to allow building plugins without building the whole thing.

When I was a developer on it, I spent a lot of time moving things in that direction, but there didn't seem to be that much interest/enthusiasm from other members of the project, so I stopped. 🤷 

Really unfortunate, because CC would be amazing if it had strong support for plugins!

**Comment by tiagodts** [comment]
Couldn't agree more. After all CC can already be seen a platform with all the great plugins that it ships with! Thanks for the reply!
